"""Catalog of free public news feeds (RSS/Atom) the News Hub reads.

Only headlines, short summaries and links are used - every story links back to the publisher's own site.
Fields: id, name, url, lang (ISO 639-1), country (ISO 3166 alpha-2), topics, note.
`note` flags publicly funded outlets so you can weigh what you read.
"""

# topics: world politics business tech science health sports entertainment environment culture
_B = "https://feeds.bbci.co.uk"

SOURCES = [
    # ---- English: world -------------------------------------------------------------------
    ("bbc_world", "BBC News - World", f"{_B}/news/world/rss.xml", "en", "GB", ["world"], "public"),
    ("bbc_uk", "BBC News - UK", f"{_B}/news/uk/rss.xml", "en", "GB", ["world", "politics"], "public"),
    ("bbc_business", "BBC - Business", f"{_B}/news/business/rss.xml", "en", "GB", ["business"], "public"),
    ("bbc_tech", "BBC - Technology", f"{_B}/news/technology/rss.xml", "en", "GB", ["tech"], "public"),
    ("bbc_science", "BBC - Science & Environment", f"{_B}/news/science_and_environment/rss.xml", "en", "GB", ["science", "environment"], "public"),
    ("bbc_health", "BBC - Health", f"{_B}/news/health/rss.xml", "en", "GB", ["health"], "public"),
    ("bbc_ent", "BBC - Entertainment & Arts", f"{_B}/news/entertainment_and_arts/rss.xml", "en", "GB", ["entertainment", "culture"], "public"),
    ("bbc_sport", "BBC Sport", f"{_B}/sport/rss.xml", "en", "GB", ["sports"], "public"),
    ("guardian_world", "The Guardian - World", "https://www.theguardian.com/world/rss", "en", "GB", ["world"], ""),
    ("guardian_tech", "The Guardian - Technology", "https://www.theguardian.com/technology/rss", "en", "GB", ["tech"], ""),
    ("guardian_science", "The Guardian - Science", "https://www.theguardian.com/science/rss", "en", "GB", ["science"], ""),
    ("guardian_business", "The Guardian - Business", "https://www.theguardian.com/uk/business/rss", "en", "GB", ["business"], ""),
    ("guardian_env", "The Guardian - Environment", "https://www.theguardian.com/environment/rss", "en", "GB", ["environment"], ""),
    ("guardian_sport", "The Guardian - Sport", "https://www.theguardian.com/sport/rss", "en", "GB", ["sports"], ""),
    ("guardian_culture", "The Guardian - Culture", "https://www.theguardian.com/culture/rss", "en", "GB", ["culture", "entertainment"], ""),
    ("npr_news", "NPR News", "https://feeds.npr.org/1001/rss.xml", "en", "US", ["world", "politics"], "public"),
    ("npr_tech", "NPR - Technology", "https://feeds.npr.org/1019/rss.xml", "en", "US", ["tech"], "public"),
    ("npr_science", "NPR - Science", "https://feeds.npr.org/1007/rss.xml", "en", "US", ["science"], "public"),
    ("npr_health", "NPR - Health", "https://feeds.npr.org/1128/rss.xml", "en", "US", ["health"], "public"),
    ("nyt_world", "New York Times - World", "https://rss.nytimes.com/services/xml/rss/nyt/World.xml", "en", "US", ["world"], ""),
    ("nyt_tech", "New York Times - Technology", "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml", "en", "US", ["tech"], ""),
    ("nyt_science", "New York Times - Science", "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml", "en", "US", ["science"], ""),
    ("nyt_business", "New York Times - Business", "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml", "en", "US", ["business"], ""),
    ("nyt_health", "New York Times - Health", "https://rss.nytimes.com/services/xml/rss/nyt/Health.xml", "en", "US", ["health"], ""),
    ("nyt_arts", "New York Times - Arts", "https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml", "en", "US", ["culture", "entertainment"], ""),
    ("aljazeera_en", "Al Jazeera English", "https://www.aljazeera.com/xml/rss/all.xml", "en", "QA", ["world"], "public"),
    ("dw_en", "Deutsche Welle", "https://rss.dw.com/rdf/rss-en-all", "en", "DE", ["world"], "public"),
    ("france24_en", "France 24", "https://www.france24.com/en/rss", "en", "FR", ["world"], "public"),
    ("euronews_en", "Euronews", "https://www.euronews.com/rss?format=mrss", "en", "FR", ["world"], ""),
    ("sky_world", "Sky News - World", "https://feeds.skynews.com/feeds/rss/world.xml", "en", "GB", ["world"], ""),
    ("un_news", "UN News", "https://news.un.org/feed/subscribe/en/news/all/rss.xml", "en", "US", ["world", "politics"], "public"),
    ("abc_au", "ABC News Australia", "https://www.abc.net.au/news/feed/51120/rss.xml", "en", "AU", ["world"], "public"),
    ("rnz", "Radio New Zealand", "https://www.rnz.co.nz/rss/national.xml", "en", "NZ", ["world"], "public"),
    ("cbc", "CBC News", "https://www.cbc.ca/webfeed/rss/rss-topstories", "en", "CA", ["world", "politics"], "public"),
    ("rte", "RTE News (Ireland)", "https://www.rte.ie/news/rss/news-headlines.xml", "en", "IE", ["world"], "public"),
    ("japantimes", "The Japan Times", "https://www.japantimes.co.jp/feed/", "en", "JP", ["world"], ""),
    ("nhk_en", "NHK World-Japan", "https://www3.nhk.or.jp/rss/news/cat0.xml", "ja", "JP", ["world"], "public"),
    ("scmp", "South China Morning Post", "https://www.scmp.com/rss/91/feed", "en", "HK", ["world", "business"], ""),
    ("straitstimes", "The Straits Times", "https://www.straitstimes.com/news/world/rss.xml", "en", "SG", ["world"], ""),
    ("cna", "CNA (Singapore)", "https://www.channelnewsasia.com/rssfeeds/8395986", "en", "SG", ["world"], ""),
    ("yonhap", "Yonhap News (Korea)", "https://en.yna.co.kr/RSS/news.xml", "en", "KR", ["world"], "public"),
    ("timesofindia", "The Times of India", "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", "en", "IN", ["world"], ""),
    ("thehindu", "The Hindu", "https://www.thehindu.com/news/international/feeder/default.rss", "en", "IN", ["world"], ""),
    ("dawn", "Dawn (Pakistan)", "https://www.dawn.com/feeds/home", "en", "PK", ["world"], ""),
    ("bangkokpost", "Bangkok Post", "https://www.bangkokpost.com/rss/data/topstories.xml", "en", "TH", ["world"], ""),
    ("jakartapost", "The Jakarta Post", "https://www.thejakartapost.com/rss", "en", "ID", ["world"], ""),
    ("hurriyet", "Hurriyet Daily News", "https://www.hurriyetdailynews.com/rss", "en", "TR", ["world"], ""),
    ("timesofisrael", "The Times of Israel", "https://www.timesofisrael.com/feed/", "en", "IL", ["world"], ""),
    ("kyivindep", "The Kyiv Independent", "https://kyivindependent.com/feed/", "en", "UA", ["world", "politics"], ""),
    ("africanews", "Africanews", "https://www.africanews.com/feed/rss", "en", "CG", ["world"], ""),
    ("mg_za", "Mail & Guardian (South Africa)", "https://mg.co.za/feed/", "en", "ZA", ["world", "politics"], ""),
    ("news24", "News24 (South Africa)", "https://feeds.news24.com/articles/news24/TopStories/rss", "en", "ZA", ["world"], ""),
    ("punch", "Punch (Nigeria)", "https://punchng.com/feed/", "en", "NG", ["world"], ""),
    ("dailynation", "Daily Nation (Kenya)", "https://nation.africa/kenya/rss.xml", "en", "KE", ["world"], ""),
    # ---- English: tech / science / health / sport / business -------------------------------
    ("hn", "Hacker News", "https://hnrss.org/frontpage", "en", "US", ["tech"], ""),
    ("arstechnica", "Ars Technica", "https://feeds.arstechnica.com/arstechnica/index", "en", "US", ["tech", "science"], ""),
    ("verge", "The Verge", "https://www.theverge.com/rss/index.xml", "en", "US", ["tech"], ""),
    ("techcrunch", "TechCrunch", "https://techcrunch.com/feed/", "en", "US", ["tech", "business"], ""),
    ("wired", "WIRED", "https://www.wired.com/feed/rss", "en", "US", ["tech"], ""),
    ("engadget", "Engadget", "https://www.engadget.com/rss.xml", "en", "US", ["tech"], ""),
    ("nasa", "NASA", "https://www.nasa.gov/rss/dyn/breaking_news.rss", "en", "US", ["science"], "public"),
    ("sciencedaily", "ScienceDaily", "https://www.sciencedaily.com/rss/all.xml", "en", "US", ["science", "health"], ""),
    ("physorg", "Phys.org", "https://phys.org/rss-feed/", "en", "GB", ["science"], ""),
    ("nature", "Nature", "https://www.nature.com/nature.rss", "en", "GB", ["science"], ""),
    ("newscientist", "New Scientist", "https://www.newscientist.com/feed/home/", "en", "GB", ["science"], ""),
    ("who", "World Health Organization", "https://www.who.int/rss-feeds/news-english.xml", "en", "CH", ["health"], "public"),
    ("mongabay", "Mongabay", "https://news.mongabay.com/feed/", "en", "US", ["environment"], ""),
    ("cnbc", "CNBC", "https://www.cnbc.com/id/100003114/device/rss/rss.html", "en", "US", ["business"], ""),
    ("espn", "ESPN", "https://www.espn.com/espn/rss/news", "en", "US", ["sports"], ""),
    ("skysports", "Sky Sports", "https://www.skysports.com/rss/12040", "en", "GB", ["sports"], ""),
    ("variety", "Variety", "https://variety.com/feed/", "en", "US", ["entertainment"], ""),
    # ---- Other languages ---------------------------------------------------------------------
    ("dw_de", "Deutsche Welle (Deutsch)", "https://rss.dw.com/rdf/rss-de-all", "de", "DE", ["world"], "public"),
    ("dw_es", "Deutsche Welle (Espanol)", "https://rss.dw.com/rdf/rss-sp-all", "es", "DE", ["world"], "public"),
    ("dw_ar", "Deutsche Welle (Arabic)", "https://rss.dw.com/rdf/rss-ar-all", "ar", "DE", ["world"], "public"),
    ("dw_ru", "Deutsche Welle (Russian)", "https://rss.dw.com/rdf/rss-ru-all", "ru", "DE", ["world"], "public"),
    ("dw_tr", "Deutsche Welle (Turkce)", "https://rss.dw.com/rdf/rss-tr-all", "tr", "DE", ["world"], "public"),
    ("dw_pt", "Deutsche Welle (Portugues)", "https://rss.dw.com/rdf/rss-br-all", "pt", "DE", ["world"], "public"),
    ("dw_hi", "Deutsche Welle (Hindi)", "https://rss.dw.com/rdf/rss-hi-all", "hi", "DE", ["world"], "public"),
    ("dw_bn", "Deutsche Welle (Bangla)", "https://rss.dw.com/rdf/rss-bn-all", "bn", "DE", ["world"], "public"),
    ("dw_id", "Deutsche Welle (Indonesia)", "https://rss.dw.com/rdf/rss-id-all", "id", "DE", ["world"], "public"),
    ("dw_zh", "Deutsche Welle (Chinese)", "https://rss.dw.com/rdf/rss-chi-all", "zh", "DE", ["world"], "public"),
    ("dw_uk", "Deutsche Welle (Ukrainian)", "https://rss.dw.com/rdf/rss-ukr-all", "uk", "DE", ["world"], "public"),
    ("france24_fr", "France 24 (Francais)", "https://www.france24.com/fr/rss", "fr", "FR", ["world"], "public"),
    ("france24_es", "France 24 (Espanol)", "https://www.france24.com/es/rss", "es", "FR", ["world"], "public"),
    ("france24_ar", "France 24 (Arabic)", "https://www.france24.com/ar/rss", "ar", "FR", ["world"], "public"),
    ("rfi_fr", "RFI (Francais)", "https://www.rfi.fr/fr/rss", "fr", "FR", ["world"], "public"),
    ("lemonde", "Le Monde", "https://www.lemonde.fr/rss/une.xml", "fr", "FR", ["world", "politics"], ""),
    ("elpais", "EL PAIS", "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada", "es", "ES", ["world", "politics"], ""),
    ("infobae", "Infobae", "https://www.infobae.com/arc/outboundfeeds/rss/", "es", "AR", ["world"], ""),
    ("bbc_mundo", "BBC Mundo", f"{_B}/mundo/rss.xml", "es", "GB", ["world"], "public"),
    ("bbc_arabic", "BBC Arabic", f"{_B}/arabic/rss.xml", "ar", "GB", ["world"], "public"),
    ("bbc_hindi", "BBC Hindi", f"{_B}/hindi/rss.xml", "hi", "GB", ["world"], "public"),
    ("bbc_russian", "BBC Russian", f"{_B}/russian/rss.xml", "ru", "GB", ["world"], "public"),
    ("bbc_portuguese", "BBC Brasil", f"{_B}/portuguese/rss.xml", "pt", "GB", ["world"], "public"),
    ("bbc_swahili", "BBC Swahili", f"{_B}/swahili/rss.xml", "sw", "GB", ["world"], "public"),
    ("bbc_persian", "BBC Persian", f"{_B}/persian/rss.xml", "fa", "GB", ["world"], "public"),
    ("bbc_urdu", "BBC Urdu", f"{_B}/urdu/rss.xml", "ur", "GB", ["world"], "public"),
    ("bbc_bengali", "BBC Bengali", f"{_B}/bengali/rss.xml", "bn", "GB", ["world"], "public"),
    ("bbc_indonesian", "BBC Indonesia", f"{_B}/indonesia/rss.xml", "id", "GB", ["world"], "public"),
    ("bbc_vietnamese", "BBC Vietnamese", f"{_B}/vietnamese/rss.xml", "vi", "GB", ["world"], "public"),
    ("bbc_korean", "BBC Korean", f"{_B}/korean/rss.xml", "ko", "GB", ["world"], "public"),
    ("bbc_thai", "BBC Thai", f"{_B}/thai/rss.xml", "th", "GB", ["world"], "public"),
    ("bbc_chinese", "BBC Chinese", f"{_B}/zhongwen/simp/rss.xml", "zh", "GB", ["world"], "public"),
    ("bbc_turkce", "BBC Turkce", f"{_B}/turkce/rss.xml", "tr", "GB", ["world"], "public"),
    ("bbc_ukrainian", "BBC Ukrainian", f"{_B}/ukrainian/rss.xml", "uk", "GB", ["world"], "public"),
    ("bbc_hausa", "BBC Hausa", f"{_B}/hausa/rss.xml", "ha", "GB", ["world"], "public"),
    ("bbc_amharic", "BBC Amharic", f"{_B}/amharic/rss.xml", "am", "GB", ["world"], "public"),
    ("bbc_pashto", "BBC Pashto", f"{_B}/pashto/rss.xml", "ps", "GB", ["world"], "public"),
    ("bbc_nepali", "BBC Nepali", f"{_B}/nepali/rss.xml", "ne", "GB", ["world"], "public"),
    ("bbc_tamil", "BBC Tamil", f"{_B}/tamil/rss.xml", "ta", "GB", ["world"], "public"),
    ("bbc_marathi", "BBC Marathi", f"{_B}/marathi/rss.xml", "mr", "GB", ["world"], "public"),
    ("bbc_gujarati", "BBC Gujarati", f"{_B}/gujarati/rss.xml", "gu", "GB", ["world"], "public"),
    ("bbc_burmese", "BBC Burmese", f"{_B}/burmese/rss.xml", "my", "GB", ["world"], "public"),
    ("bbc_somali", "BBC Somali", f"{_B}/somali/rss.xml", "so", "GB", ["world"], "public"),
    ("bbc_kyrgyz", "BBC Kyrgyz", f"{_B}/kyrgyz/rss.xml", "ky", "GB", ["world"], "public"),
    ("bbc_uzbek", "BBC Uzbek", f"{_B}/uzbek/rss.xml", "uz", "GB", ["world"], "public"),
    ("bbc_azeri", "BBC Azeri", f"{_B}/azeri/rss.xml", "az", "GB", ["world"], "public"),
    ("bbc_serbian", "BBC Serbian", f"{_B}/serbian/lat/rss.xml", "sr", "GB", ["world"], "public"),
    ("bbc_afrique", "BBC Afrique", f"{_B}/afrique/rss.xml", "fr", "GB", ["world"], "public"),
    ("g1", "G1 (Globo, Brazil)", "https://g1.globo.com/rss/g1/", "pt", "BR", ["world"], ""),
    ("folha", "Folha de S.Paulo", "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml", "pt", "BR", ["world", "politics"], ""),
    ("nhk_ja", "NHK News (Japanese)", "https://www3.nhk.or.jp/rss/news/cat0.xml", "ja", "JP", ["world"], "public"),
    ("spiegel", "DER SPIEGEL", "https://www.spiegel.de/schlagzeilen/index.rss", "de", "DE", ["world", "politics"], ""),
    ("tagesschau", "tagesschau", "https://www.tagesschau.de/index~rss2.xml", "de", "DE", ["world", "politics"], "public"),
    ("ansa", "ANSA (Italian)", "https://www.ansa.it/sito/ansait_rss.xml", "it", "IT", ["world"], ""),
    ("corriere", "Corriere della Sera", "https://xml2.corriereobjects.it/rss/homepage.xml", "it", "IT", ["world", "politics"], ""),
    ("aljazeera_ar", "Al Jazeera (Arabic)", "https://www.aljazeera.net/aljazeerarss/a7c186be-1baa-4bd4-9d80-a84db769f779/73d0e1b4-532f-45ef-b135-bfdff8b8cab9", "ar", "QA", ["world"], "public"),
    ("vnexpress", "VnExpress (Vietnamese)", "https://vnexpress.net/rss/tin-moi-nhat.rss", "vi", "VN", ["world"], ""),
    ("kompas", "Kompas (Indonesian)", "https://www.kompas.com/rss", "id", "ID", ["world"], ""),
    ("hurriyet_tr", "Hurriyet (Turkish)", "https://www.hurriyet.com.tr/rss/anasayfa", "tr", "TR", ["world"], ""),
    ("meduza", "Meduza (Russian)", "https://meduza.io/rss/all", "ru", "LV", ["world", "politics"], ""),
    ("pravda_ua", "Ukrainska Pravda", "https://www.pravda.com.ua/rss/", "uk", "UA", ["world", "politics"], ""),
    ("gazeta_pl", "Gazeta Wyborcza (Polish)", "https://wyborcza.pl/pub/rss/wyborcza.xml", "pl", "PL", ["world"], ""),
    ("nos_nl", "NOS (Dutch)", "https://feeds.nos.nl/nosnieuwsalgemeen", "nl", "NL", ["world"], "public"),
    ("svt_sv", "SVT Nyheter (Swedish)", "https://www.svt.se/nyheter/rss.xml", "sv", "SE", ["world"], "public"),
    ("yle_fi", "Yle Uutiset (Finnish)", "https://feeds.yle.fi/uutiset/v1/majorHeadlines/YLE_UUTISET.rss", "fi", "FI", ["world"], "public"),
    ("dr_da", "DR Nyheder (Danish)", "https://www.dr.dk/nyheder/service/feeds/allenyheder", "da", "DK", ["world"], "public"),
    ("nrk_no", "NRK (Norwegian)", "https://www.nrk.no/toppsaker.rss", "no", "NO", ["world"], "public"),
    ("ert_gr", "ERT (Greek)", "https://www.ertnews.gr/feed/", "el", "GR", ["world"], "public"),
    ("hani_ko", "Hankyoreh (Korean)", "https://www.hani.co.kr/rss/", "ko", "KR", ["world"], ""),
    ("ynet_he", "Ynet (Hebrew)", "https://www.ynet.co.il/Integration/StoryRss2.xml", "he", "IL", ["world"], ""),
    ("mid_bg", "BNR (Bulgarian)", "https://bnr.bg/rss", "bg", "BG", ["world"], "public"),
]


def catalog():
    keys = ("id", "name", "url", "lang", "country", "topics", "note")
    return [dict(zip(keys, s)) for s in SOURCES]
